on: [push, pull_request]

name: Test and Build

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['>=20.10', '22.x']
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify versions
        run: node --version && npm --version && node -p process.versions.v8

      - name: Cache build artifacts
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: test-${{ runner.os }}-node-${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build
